language: python
dist: bionic

virtualenv:
  system_site_packages: true

before_install:
  - sudo apt-get install python3 python3-dev build-essential
  - sudo apt-get install libboost-dev libboost-system-dev libboost-python-dev

script:
  - travis_wait 240 python3 setup.py build
  - travis_wait 240 sudo python3 setup.py install
  - pytest -v tests/
