name: Build

on: [push, pull_request]

jobs:
  build_wheels:
    name: Build wheel on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04]

    steps:
    - uses: actions/checkout@v1

    - uses: actions/setup-python@v1
      name: Install Python
      with:
        python-version: '3.6'

    - name: Install cibuildwheel
      run: |
        python -m pip install cibuildwheel==1.4.1

    - name: Install dependencies
      run: |
        sudo apt-get install python python3 python3-dev build-essential libboost-dev libboost-system-dev libboost-python-dev

    - name: Build wheel
      run: |
        python2 setup.py build
        python setup.py install
        python -m cibuildwheel --output-dir wheelhouse
      env:
        CIBW_SKIP: cp27-* cp35-*

    - uses: actions/upload-artifact@v1
      with:
        name: wheels
        path: ./wheelhouse
